
name: NuGet package publish
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  upload-to-npgk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: latest
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      # CHANGE PACKAGE VERSION - The retarded way
      # Change the /p:VERSION=X.X.X part to change the actual package version.
      run: dotnet pack --configuration Release /p:VERSION=1.0.0.${{ github.run_number }} --version-suffix ${{ github.sha }} 
    - name: Upload to NuGet
      run: dotnet nuget push /home/runner/work/cs-x39-util/cs-x39-util/X39.Util/bin/Release/X39.Util.*.nupkg -s https://api.nuget.org/v3/index.json
